package tk.germanbot.data

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.socialsignin.spring.data.dynamodb.repository.EnableScan
import org.springframework.data.repository.CrudRepository


@DynamoDBTable(tableName = "translation")
class Translation(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String,
        @DynamoDBAttribute
        var ge: String,
        @DynamoDBAttribute
        var en: String
)

