package tk.germanbot.data

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.socialsignin.spring.data.dynamodb.repository.EnableScan
import org.springframework.data.repository.CrudRepository


@DynamoDBTable(tableName = "translation")
data class Translation(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        var de: String?,
        @DynamoDBAttribute
        var en: String?
)

@EnableScan
interface TranslationRepository : CrudRepository<Translation, String> {
    fun findOneById(id: String): Translation

    override fun findAll(): List<Translation>
    fun findByDe(de: String): List<Translation>
    fun findByEn(en: String): List<Translation>
}

